# Generated by Django 3.2.9 on 2022-05-16 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
