# Generated by Django 3.2.9 on 2022-01-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80)),
                ('category_info', models.CharField(max_length=300)),
                ('category_slug', models.CharField(default='All in', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categoryes',
            },
        ),
    ]
