# Generated by Django 3.2.9 on 2022-02-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contetn',
            new_name='content',
        ),
    ]
